version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  
  fuxa:
    image: frangoteam/fuxa
    ports:
      - "1881:1881"
    volumes:
      - ./fuxa/data:/data